version: "3"
services:
  nodestatus:
    image: cokemine/nodestatus
    restart: always

    environment:
      INTERVAL: 1500
      DATABASE: mysql://root:LzJTPsEk2TGwnicKjK2T@containers-us-west-25.railway.app:6317/railway
      PORT: 35601
      VERBOSE: "false"
      THEME: "hotaru-theme"

      USE_PUSH: "true"
      USE_IPC: "true"
      USE_WEB: "true"

      WEB_USERNAME: "ironhide"
      WEB_PASSWORD: "wang1234"
      WEB_SECRET: ""


      PUSH_TIMEOUT: 30
      PUSH_DELAY: 15
      TGBOT_TOKEN: ""
      TGBOT_CHATID: ""
      TGBOT_PROXY: ""
      TGBOT_WEBHOOK: ""

    volumes:
      - /usr/local/NodeStatus/server:/usr/local/NodeStatus/server
      - /tmp:/tmp:rw

    ports:
      - "35601:35601"

